name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.3'
    - name: Build tests
      working-directory: source
      run: ghc -Wall -O3 -Werror Runtest.hs -o ../test
    - name: Run tests
      run: ./test
